name: DRC Files
on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'

  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      
  workflow_dispatch:

jobs:
  drc-files:
    name: DRC Everything
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad8_auto:1.6.5
      
    steps:

    - name: Generate Short SHA Environment Variable
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: DRC PB_16v1 Files
      run: |
        cd PB_16v1
        rm -rf PB_16v1/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d PB_16v1

    - name: DRC PB_16v2_SMD Files
      run: |
        cd PB_16v2_SMD
        rm -rf PB_16v2_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d PB_16v2_SMD

    - name: DRC PB_16_Expansion Files
      run: |
        cd PB_16_Expansion
        rm -rf PB_16_Expansion/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d PB_16_Expansion

    - name: DRC PB_16_Flex Files
      run: |
        cd PB_16_Flex
        rm -rf PB_16_Flex/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d PB_16_Flex

    - name: DRC PB_16_Mini Files
      run: |
        cd PB_16_Mini
        rm -rf PB_16_Mini/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d PB_16_Mini

    - name: DRC BBB_16 Files
      run: |
        cd BBB_16
        rm -rf BBB_16/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e BBB_16.kicad_sch -b BBB_16.kicad_pcb -d BBB_16

    - name: DRC BBB_16_SMD Files
      run: |
        cd BBB_16_SMD
        rm -rf BBB_16_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e BBB_16.kicad_sch -b BBB_16.kicad_pcb -d BBB_16_SMD

    - name: DRC BBB_16_Expansion Files
      run: |
        cd BBB_16_Expansion
        rm -rf BBB_16_Expansion/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e BBB_16_Expansion.kicad_sch -b BBB_16_Expansion.kicad_pcb -d BBB_16_Expansion

    - name: DRC BBB_16_Flex Files
      run: |
        cd BBB_16_Flex
        rm -rf BBB_16_Flex/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e BBB_16_Flex.kicad_sch -b BBB_16_Flex.kicad_pcb -d BBB_16_Flex

    - name: DRC 16_Expansion Files
      run: |
        cd 16_Expansion
        rm -rf 16_Expansion/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d 16_Expansion

    - name: DRC 16_Expansion_24pin Files
      run: |
        cd 16_Expansion_24pin
        rm -rf 16_Expansion_24pin/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d 16_Expansion_24pin

    - name: DRC 16_Expansion_Dual_SMD Files
      run: |
        cd 16_Expansion_Dual_SMD
        rm -rf 16_Expansion_Dual_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d 16_Expansion_Dual_SMD

    - name: DRC 16_Expansion_SMD Files
      run: |
        cd 16_Expansion_SMD
        rm -rf 16_Expansion_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d 16_Expansion_SMD

    - name: DRC 16_Expansion_SMD_24pin Files
      run: |
        cd 16_Expansion_SMD_24pin
        rm -rf 16_Expansion_SMD_24pin/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB_16.kicad_sch -b PB_16.kicad_pcb -d 16_Expansion_SMD_24pin

    - name: DRC Diff_Expansion Files
      run: |
        cd Diff_Expansion
        rm -rf Diff_Expansion/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Diff_Expansion.kicad_sch -b Diff_Expansion.kicad_pcb -d Diff_Expansion

    - name: DRC Multi_Expansion Files
      run: |
        cd Multi_Expansion
        rm -rf Multi_Expansion/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Multi_Expansion.kicad_sch -b Multi_Expansion.kicad_pcb -d Multi_Expansion

    - name: DRC Receiver_Out Files
      run: |
        cd Receiver_Out
        rm -rf Receiver_Out/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Receiver_Out.kicad_sch -b Receiver_Out.kicad_pcb -d Receiver_Out

    - name: DRC Receiver_Out_SMD Files
      run: |
        cd Receiver_Out_SMD
        rm -rf Receiver_Out_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Receiver_Out.kicad_sch -b Receiver_Out.kicad_pcb -d Receiver_Out_SMD

    - name: DRC SM_Receiver_Out_SMD Files
      run: |
        cd SM_Receiver_Out_SMD
        rm -rf SM_Receiver_Out_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Receiver_Out.kicad_sch -b Receiver_Out.kicad_pcb -d SM_Receiver_Out_SMD

    - name: DRC Input_Adapter Files
      run: |
        cd Input_Adapter
        rm -rf Input_Adapter/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Input_Adapter.kicad_sch -b Input_Adapter.kicad_pcb -d Input_Adapter

    - name: DRC Four_Out Files
      run: |
        cd Four_Out
        rm -rf Four_Out/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Four_Out.kicad_sch -b Four_Out.kicad_pcb -d Four_Out

    - name: DRC PB16_2_PI Files
      run: |
        cd PB16_2_PI
        rm -rf PB16_2_PI/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e PB16_2_PI.kicad_sch -b PB16_2_PI.kicad_pcb -d PB16_2_PI

    - name: DRC Pi_Zero_W_16_SMD Files
      run: |
        cd Pi_Zero_W_16_SMD
        rm -rf Pi_Zero_W_16_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Pi_Zero_W_16.kicad_sch -b Pi_Zero_W_16.kicad_pcb -d Pi_Zero_W_16_SMD

    - name: DRC Pi_Zero_24_Diff_SMD Files
      run: |
        cd Pi_Zero_24_Diff_SMD
        rm -rf Pi_Zero_24_Diff_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Pi_Zero_24_Diff.kicad_sch -b Pi_Zero_24_Diff.kicad_pcb -d Pi_Zero_24_Diff_SMD

    - name: DRC Pi_Zero_Expansion_SMD Files
      run: |
        cd Pi_Zero_Expansion_SMD
        rm -rf Pi_Zero_Expansion_SMD/
        kibot -c ../.github/workflows/scripts/kibot/drc.config.kibot.yaml -e Pi_Zero_Expansion.kicad_sch -b Pi_Zero_Expansion.kicad_pcb -d Pi_Zero_Expansion_SMD


    - name: Upload Export Files as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: |
          PB_16v1/PB_16v1/**
          PB_16v2_SMD/PB_16v2_SMD/**
          PB_16_Expansion/PB_16_Expansion/**
          PB_16_Flex/PB_16_Flex/**
          PB_16_Mini/PB_16_Mini/**
          BBB_16/BBB_16/**
          BBB_16_SMD/BBB_16_SMD/**
          BBB_16_Expansion/BBB_16_Expansion/**
          BBB_16_Flex/BBB_16_Flex/**
          16_Expansion/16_Expansion/**
          16_Expansion_24pin/16_Expansion_24pin/**
          16_Expansion_Dual_SMD/16_Expansion_Dual_SMD/**
          16_Expansion_SMD/16_Expansion_SMD/**
          16_Expansion_SMD_24pin/16_Expansion_SMD_24pin/**
          Diff_Expansion/Diff_Expansion/**
          Multi_Expansion/Multi_Expansion/**
          Receiver_Out/Receiver_Out/**
          Receiver_Out_SMD/Receiver_Out_SMD/**
          SM_Receiver_Out_SMD/SM_Receiver_Out_SMD/**
          Input_Adapter/Input_Adapter/**
          Four_Out/Four_Out/**
          PB16_2_PI/PB16_2_PI/**
          Pi_Zero_W_16_SMD/Pi_Zero_W_16_SMD/**
          Pi_Zero_24_Diff_SMD/Pi_Zero_24_Diff_SMD/**
          Pi_Zero_Expansion_SMD/Pi_Zero_Expansion_SMD/**
        if-no-files-found: error
        retention-days: 60

